---
- name: ensures {{ firewall_pkg }} is  installed
  ansible.builtin.dnf:
                     name: "{{ firewall_pkg }}"
                     state: latest
                       
- name: ensure {{ firewall_svc }} is running
  ansible.builtin.service:
                       name: "{{ firewall_svc }}"
                       state: started
                       enabled: true
- name: allow service through the firewall
  ansible.posix.firewalld:
    service: "{{ app_service }}"
    permanent: yes
    state: enabled
    immediate: true
  when: ansible_distribution == "RedHat"     
